x12345 = ('x' for x in [1 .. 12345]).join ''
itShould 'work with no characters', 'echo -n | ./wc', '0 0 0\n'
itShould 'work with a single character', 'echo -n a | ./wc', '1 1 0\n'
itShould 'work with an empty line', 'echo | ./wc', '1 0 1\n'
itShould 'work with two empty lines', '(echo; echo) | ./wc', '2 0 2\n'
itShould 'work with a single character and line', 'echo a | ./wc', '2 1 1\n'
itShould 'work with a single word', 'echo hello | ./wc', '6 1 1\n'
itShould 'work with a larger file', "echo -n #{x12345} | ./wc", '12345 1 0\n'
