#!/bin/bash

root=$(cd "$(dirname $BASH_SOURCE)"; pwd)

main() {
  cd "$root"

  if [[ $1 ]]; then
    "$@"
    return
  fi

  rsync -a --del src/ build-dir/
  mkdir -p bin

  cd build-dir
  local program
  for file in $(ls -1 | egrep '.asm$' | egrep -v '^_'); do
    ../scripts/a "$file"
    mv "$(basename "$file" .asm)" ../bin
  done
  cd "$root"
  rm -fr build-dir
}

test() {
  export PATH+=":$root/node_modules/.bin"
  mocha -s 500 --compilers coffee:coffee-script/register
}

main "$@"
