#!/bin/bash

root=$(cd "$(dirname $BASH_SOURCE)"; pwd)

main() {
  cd "$root"
  export PATH+=":$root/node_modules/.bin"
  mocha -s 500 test/index.coffee --compilers coffee:coffee-script/register -g "${1:-.*}"
}

main "$@"
