#!/usr/bin/env bash

set -e

main() {
    local name=$(basename "$1" .asm)
    if [[ "$2" == '--debug' ]]; then
        nasm -g -f elf64 "$1"
    else
        nasm -f elf64 "$1"
    fi
    ld -o "$name" "$name".o
    if [[ "$2" != '--debug' ]]; then
        strip --strip-all "$name"
        strip --remove-section=.note.gnu.build-id "$name"
    fi
    rm "$name".o
}

main "$@"
