%ifndef MACROS_MAC
%define MACROS_MAC

%define small_buf_size 4096

# http://blog.rchapman.org/post/36801038863/linux-system-call-table-for-x86-64
%define syscall_read 0
%define syscall_write 1
%define syscall_exit 60

%define stdin_fileno 0
%define stdout_fileno 1

%define exit_success_code 0

%define chr_space 32
%define chr_line_feed 10
%define chr_a_upper 65
%define chr_z_upper 90
%define chr_a_lower 97
%define chr_z_lower 122
%define chr_underscore 95

%endif
